### ISSUE TITLE
Question about searchDocuments method parameters.

### ISSUE THREAD

**Issue by lgryn** [Nexucis/es-php-index-helper#13]
Hey. Durning `index-helper` usage in my project I found that I need more functionality from `searchDocuments` method ). But if we add more params to it probably it will overflow. What about add ability to pass `searchDocuments($alias, $params)` or  `searchDocuments($alias, $query, $params)` where `$params` will be array with parameters what supported by `Elasticsearch\Client::search` method?

**Comment by Nexucis** [comment]
Hello,
As we use php7, I was thinking to use an object instead of an array and use the Builder pattern. This object will have as attribute each paramater that `Elasticsearch\Client::search` method supported.
I think that maybe on this way it will be more "developer" friendly.

**Comment by Nexucis** [comment]
But definitely it will be better to have something that doesn't reduce the parameter for the search method, I'm agree with you on that :)

**Comment by lgryn** [comment]
For me, Builder pattern looks overkill for this issue so far. But I will think about that.

**Comment by Nexucis** [comment]
Yeaah, reading again what I wrote, that's not the builder pattern that I has in mind, or at least not completely.

I was thinking something like this :

```php
<?php

namespace Nexucis\Elasticsearch\Helper\Nodowntime;

class SearchParameter
{
    protected $analyzer;

    protected $explain;
    protected $fields;

    public function __construct()
    {
    }

    public function analyzer(string $analyzer)
    {
        $this->analyzer = $analyzer;
        return $this;
    }

}
```

And after that you can use this object like this : 

```php
$helper->search('myIndex', null, 0, 10, new SearchParameter()->analyzer("something"))
```

That's just an example to illustrate what I have in mind :). Maybe with this kind of object it will be a good idea to just left as the parameter of the search method, just the alias and the object.

Moreover using a object to set the search parameter will prevent the developer to put a parameter that doesn't exists. So on this way you'll save some development time

**Comment by lgryn** [comment]
Yep, it makes sense, I like this approach.

**Comment by Nexucis** [comment]
By the way, I'll be too busy for the next couple of weeks. So if you want to do it on yourself and make a pull request, I'll be more than happy :). But if you don't want, that's ok ^^

**Comment by lgryn** [comment]
I will take care of this soon as possible when I will have free time. Probably it's will be faster than a couple weeks)

**Comment by Nexucis** [comment]
Hello,

I found some times to do it finally :). Thanks for the suggestion !.

The issue is closed since the code shall fit your needs. Don't hesitate to give a feedback about it, on this issue or on another one if you want some other improvement.
